Sangkyeong
the-kingdoms/study-fe pull request #4
Opened 2023-06-29 04:22 UTC by VsangkyeongV

2023-06-29 09:48 UTC, DeveloperRyou requested changes
전반적으로 코드 작성하신 걸 잘 보고 리뷰했습니다.

기본적으로 수정해야할 부분입니다.
1. 디렉토리를 형성해주세요
- sangkyeong
  - FW.css
  - FW.html ...


이후 각 리뷰별 수정해야 할 부분을 수정해주시면 됩니다.

2023-06-29 09:48 UTC, DeveloperRyou commented on FW.css
> +}
이런 부분은 
```css
.mt-10px
.mb-30px
```
와 같은 클래스명이 훨신 더 직관적이겠죠.
실제로 스터디 기간동안만 css를 직접 짜게 될거고 이런 형태의 기본 css 클래스들은 추후에 라이브러리를 사용할 예정입니다.

https://tailwindcss.com/

요즘 떠오르는 css 라이브러리인데 한번 방문해서 어떤 느낌의 클래스가 사용되는지 확인해보세요!

2023-06-29 09:48 UTC, DeveloperRyou commented on FW.css
> +}
지금 보시면, 이런 기본 속성을 정의하는 css가 뚝뚝 떨어져 있는걸 볼 수 있어요.
프로젝트 진행하면서 파일이 이렇게 구성된다면, 유지보수성이 떨어져서 나중에는 코드 읽는 시간 8, 짜는 시간 2 와 같이 생산성이 악화될 수도 있습니다.

읽기 좋은 파일의 줄 수는 대략 50~100줄이라고 합니다.
- default.css
- button.css
- main.css 
등(파일 이름, 구분 방식은 자유) 으로 3개의 css 파일로 구성해 주세요!

2023-06-29 09:48 UTC, DeveloperRyou commented on FW.html
> +      </div>
이 구조에서 정확히 절반 절반으로 이미지가 구성되어야 하는데, flex 아래의 html 태그을 살펴보면, 2번째 이미지가 레이아웃 바깥으로 빠져나가 있어요.

확인후 수정 바랍니다.

2023-06-29 09:48 UTC, DeveloperRyou commented on FW.html
> +    <script src="./FW.js"></script>
지금 아마 이 스크립트의 기능 (5개 문자 이상 입력 후 버튼 클릭시 alert 호출) 이 동작하지 않을 것입니다.
이유로는 html 태크가 다 불러와지기 전에 script를 불러와서, 어떤 html요소를 찾을 지 몰라 getElementById 가 null을 반환하기 때문인데요,
해결하기 위해서는 body 태그 밑으로 script 태그를 내려보세요!

2023-06-29 09:48 UTC, DeveloperRyou commented on FW.js
> +  }
disable이 잘 되는걸 확인했어요. (스크립트 태그 위치 조정 후)
그러나 활성화 상태를 user가 보려면 색이 바뀌어야 할텐데, 이 기능을 넣으려면 어떻게 구성해야 할까요?

2023-06-30 03:28 UTC, VsangkyeongV commented
리뷰 감사합니다 말씀주신대로 수정하겠습니다

2023-07-03 22:10 UTC, DeveloperRyou approved these changes
0주차 과제 마무리 하신걸 확인했습니다.
css분리하시면서 중복된 속성은 제거해주시는거 이외에 특이한 점은 없었습니다!

2023-07-03 22:10 UTC, DeveloperRyou commented on FW/FW.css
> +}
이런 부분은 이제 button.css로 분리했으니 중복을 제거해주는게 좋겠죠

2023-07-03 22:10 UTC, merged