중복된 부분 정리했습니다
the-kingdoms/study-fe pull request #9
Opened 2023-07-04 00:14 UTC by VsangkyeongV

2023-07-04 03:43 UTC, DeveloperRyou requested changes
네 확인했습니다!
컴포넌트로 분리, routing 작업 진행해주시면 될거 같습니다.
자세한 리뷰는 그 이후에 남기도록 할께요

2023-07-09 12:16 UTC, VsangkyeongV commented
state와 event, props에 대해 이해가 부족하여 다시 공부하느라 제출이 늦어졌습니다 ㅠㅠ 최대한 빨리 마무리 해서 남은 과제 제출 하겠습니다.

2023-07-09 13:33 UTC, VsangkyeongV commented on VsangekyeongV/react-project/src/components/LoginForm.tsx
> +    navigate("/main");
왜 여기서는 <Link> 컴포넌트를 쓸 수 없나요?

2023-07-10 00:08 UTC, DeveloperRyou commented on VsangekyeongV/react-project/src/components/LoginForm.tsx
> +    navigate("/main");
링크 컴포넌트는 말그대로 "컴포넌트"라서 사용방법이 <Link /> 이런식으로 되고, 컴포넌트는 기본적으로 렌더링이 되는 요소라고 생각해야 합니다.

지금 만들고 있는 LoginHandler는 함수고, 렌더링이 되는 기능이 아니기 때문에 함수 안에서는 컴포넌트를 사용하기 힘들죠.

2023-07-10 00:12 UTC, DeveloperRyou approved these changes, later dismissed

2023-07-10 00:12 UTC, DeveloperRyou commented on VsangekyeongV/react-project/public/trash/Button.tsx
public 폴더에 있는 trash 에 있는 파일들은 어떤 기능을 수행하나요?
기본적으로 사용하는 기능이라면, src로 이동하는게 맞고,
사용하지 않는 기능이라면 지우는게 맞습니다.

나중에 사용할거 같다. 참조를 위한 파일이다. 는 기본적으로는 넣지 않는게 맞아요

2023-07-10 00:12 UTC, DeveloperRyou commented on VsangekyeongV/react-project/src/components/ClonePage.tsx
> +          </a>
이 부분도 요소가 중복되니, 컴포넌트로 따로 빼고 props로 전달해도 좋겠죠

2023-07-10 00:12 UTC, DeveloperRyou commented on VsangekyeongV/react-project/src/components/LoginForm.tsx
> +    </div>
html 태그중에 form이라는 태그가 있죠. 그 태그를 사용 안하신 이유가 있을까요?

2023-07-10 01:02 UTC, VsangkyeongV commented on VsangekyeongV/react-project/public/trash/Button.tsx
넵 알겠습니다

2023-07-10 01:10 UTC, VsangkyeongV commented on VsangekyeongV/react-project/src/components/LoginForm.tsx
> +    </div>
앗 생각을 못했습니다 form을 사용하면 이점이 있을까요?

2023-07-10 09:03 UTC, DeveloperRyou commented on VsangekyeongV/react-project/src/components/LoginForm.tsx
> +    </div>
코딩 스타일 차이 이기는 한데, form 을 쓰는게 보다 명확한 태그 선언이라 유지보수에 좋다 정도 있겠네요. 또 form 을 통해 나중에 할 GET, POST 등의 요청을 바로 보낼 수 있기도 하고, onSubmit에 event를 가져와서 단순하지 않은 동작 구현할 때 사용할 수도 있습니다.

다만 그만큼 form이 복잡해지면 아마 라이브러리를 사용하게 될껀데, form 관련 라이브러리로는 useForm 훅을 가장 많이 사용하는거 같아요
https://react-hook-form.com/docs/useform

2023-07-10 09:04 UTC, DeveloperRyou approved these changes

2023-07-10 09:05 UTC, merged

2023-07-10 09:05 UTC, DeveloperRyou commented
2주차 과제도 잘해주셨습니다~